
kml2traj=function(allpoints,id=1){
	#take a dataframe generated by kml_points and convert to traj
	#allpoints = dataframe generated by kml_points
	#id = id used in ltraj
	
	require(adehabitatLT)
	#add a space between date and time
	descs=gsub("([0-9])([T])", '\\1 \\2', allpoints$description)
	#remove non numbers
	descs=gsub("[^0-9. \\:-]", "", descs)
	#remove extra spaces
 	descs=gsub("(?<=[\\s])\\s*|^\\s+|\\s+$", "", descs, perl=TRUE)
	#add a space between number and decimal points for splitting
 	descs=gsub("([0-9])(\\.)", '\\1 \\2', descs)
	#remove duplicates
	samepoints=!duplicated(descs)
	descs=descs[samepoints]
	#split by space
	descs2=strsplit(descs," ")
	#start and end points for each location
	ndates=do.call(c,lapply(descs2,function(x) c(x[1],x[4])))
	ntimes=do.call(c,lapply(descs2,function(x) c(x[2],x[5])))
	nlat=rep(allpoints$latitude[samepoints],each=2)
	nlong=rep(allpoints$longitude[samepoints],each=2)
	nnames=rep(allpoints$name[samepoints],each=2)
	ndt=as.POSIXct(strptime(paste(ndates,ntimes),format="%Y-%m-%d %H:%M:%S",tz="UTC"))
	#add a second to any points at exactly the same time
	ndt[duplicated(ndt)]=ndt[duplicated(ndt)]+1
	traj=as.ltraj(data.frame(nlong,nlat),ndt,id=id,infolocs=data.frame(nnames),proj4string=CRS("+init=epsg:4326"))
	return(traj)
}
